### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by zyg-github** [kevinzhow/producter_fuse#2]
Fuse 版本已经是 0.9.4
<img src="http://i4.tietuku.com/33789c53309e32a3.jpg">

**Comment by kevinzhow** [comment]
Pull 最新的代码重新 Compile 试试，这个是 Fuse 的内部错误，看不出来问题

**Comment by zyg-github** [comment]
代码是 下载github最新的 ~   看来 到我手的 问题总是多多  T_T

**Comment by bawn** [comment]
@zyg-github 0.95版本没问题
